# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae156ac47691e15c1532eeef12b75b613f2a01e8ace05e13c43f317337db6a878f0cf58b9da8b386656ff52519dc4ff8cd32e06ddb657d84ddfbc17c06ac5d90

test:
  secret_key_base: 30935800db3a17a301135ee003a3d5b2c173ae29d542abad94899dd922dc52e9152c84113e7602697a79a519df563dd0db045c1a8713ba471104944c164f0697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
